name: Run Unit Tests 

on: [push]

jobs:
  run-auth-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu:latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2


      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        working-directory: auth
        run: npm install

      - name: Run tests
        working-directory: auth
        run: npm run tests  